#!/bin/bash

echo "Diffing account files on login node with head node"
# arrows will point at entries from the second file, head node's
# >

echo

for fn in passwd group shadow sudoers auto.home; do
	file=/etc/$fn	
	echo "--- $file ---"
	ssh login-0-0 "cat $file" | diff - "$file" | diff - "/root/manage/diffs/$fn.expected"
	echo
done
